# Generated by Django 3.2.8 on 2021-12-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_migrate_translatable_fields'),
    ]

    operations = [
    ]
